codecov:
  notify:
    require_ci_to_pass: no
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "20...100"

  status:
    project: no
    patch: no
    changes: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
